# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
       accidents_storage:
            adapter: 'League\Flysystem\Adapter\Local'
            options:
                directory: '%kernel.project_dir%/var/data'
