#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_reservation_m:
    path: '/reservation'
    controller: App\Controller\ReservationMController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
